### ISSUE TITLE
Feature Request: Immer

### ISSUE THREAD

**Issue by TheUltDev** [YousefED/SyncedStore#102]
It would be useful to use ImmerJS similar to how Redux Toolkit includes it. I think most people used to Redux have grown accustomed to writing immutable code using a mutable api, it's much easier.

Reference: https://github.com/sep2/immer-yjs

**Comment by YousefED** [comment]
Hi @TheUltDev. Interesting suggestion! For now, I won't be able to actively work on this, but I would be open to any PRs. Also, if more requests come up for this I can reprioritize
