### ISSUE TITLE
Supporting array assignment

### ISSUE THREAD

**Issue by pierscowburn** [YousefED/SyncedStore#112]
Thanks again for a great library – it continues to be super useful in our application!

I noticed that there's a reference in the code to [array assignment not being supported](https://github.com/YousefED/SyncedStore/blob/main/packages/core/src/array.ts#L176), and have run across this when trying to use array assignment on an upcoming feature. I was wondering if you had an idea as to how much work is required in order to support this – i.e. are there gotchas you're aware of that lead to the decision not to support it yet?

**Comment by YousefED** [comment]
The reason array assignment is not supported is explained here: https://github.com/YousefED/SyncedStore/issues/59

You could indeed use splice as a workaround
