### ISSUE TITLE
How to handle relations

### ISSUE THREAD

**Issue by andrezimpel** [YousefED/SyncedStore#113]
First of all awesome project, thank you! I was wondering how to implement nested objects. Say there are todo lists that have todos. a todo has an assignee. An assignee is a user within my app.

What if the users edits his/her name, it would not automatically be reflected in the doc.

How would I handle this situation?

**Comment by YousefED** [comment]
I would create the following structure:
```
{ 
users: {
<id>: { userdata}
},
todos: [
title: "text",
completed: true,
author: <id>
]
}
```
