### ISSUE TITLE
Warning: `property not found on root doc $$typeof`

### ISSUE THREAD

**Issue by websiddu** [YousefED/SyncedStore#116]
When exporting the Synced Store object in next.js received the following warning, 

`property not found on root doc $$typeof`

Seems like we need to add $$typeof in there 

https://github.com/YousefED/SyncedStore/blob/main/packages/core/src/doc.ts#L47

Please confirm if that is correct I can submit a pull request.

**Comment by YousefED** [comment]
This might be right. If you add a PR with a unit test I'd be happy to merge!
