### ISSUE TITLE
Question: How many stores should you create?

### ISSUE THREAD

**Issue by AlexW00** [YousefED/SyncedStore#119]
I'm building a flashcards app. Until now I used PouchDB and created a new Document for each flashcard. Using SyncedStore, is it recommended to create one "flashcards" object that holds all cards or one store for each card? Note that a flashcard can contain cached html.

**Comment by YousefED** [comment]
This depends on your application. In general, I would say you only need multiple stores if you have external reasons for it, such as sharing / permissions. Documents (stores) are a good level to isolate permissions. If you don't have this boundary, it's fine (and recommended) to keep all flashcards in one store
