### ISSUE TITLE
Consider Svelte?

### ISSUE THREAD

**Issue by canadaduane** [YousefED/SyncedStore#20]
Has anyone looked at Svelte integration? It seems like a natural fit. I wrote https://svelt-yjs.dev/ which is also an attempt at making yjs easier to use for Svelte, but I like this approach better.

**Comment by YousefED** [comment]
Svelte support has just been added in #25. Still needs to be added to the documentation website, but for now I'm closing this

**Comment by YousefED** [comment]
@canadaduane looking forward to your feedback!

**Comment by canadaduane** [comment]
Very cool! I'll try to take a look soon. Exciting!
