### ISSUE TITLE
Required version of node/npm for examples

### ISSUE THREAD

**Issue by jasonm** [YousefED/SyncedStore#26]
Thanks for sharing SyncedStore! I'm digging in and starting by playing with the examples.

It looks like the package.json for the todo-react example works with npm 6.14.13 but not npm 8.1.4 (latest stable). Not sure exactly what version started the issue but the message is:

```
npm ERR! code EWORKSPACESCONFIG
npm ERR! workspaces config expects an Array
```

Gist of a shell session trying it out:
https://gist.github.com/jasonm/33e2d7a7501d3c4f6a8f7df150ed34ec

This seems to fix it:

```diff
diff --git a/examples/todo-react/package.json b/examples/todo-react/package.json
index 3ac21ec..4d3cece 100644
--- a/examples/todo-react/package.json
+++ b/examples/todo-react/package.json
@@ -44,10 +44,5 @@
       "last 1 firefox version",
       "last 1 safari version"
     ]
-  },
-  "workspaces": {
-    "nohoist": [
-      "**"
-    ]
   }
 }
```

**Comment by YousefED** [comment]
Thanks for reporting! Should be fixed
