### ISSUE TITLE
Where is @theme-init/CodeBlock?

### ISSUE THREAD

**Issue by echarles** [YousefED/SyncedStore#44]
While looking at the source code and trying out building the doc site, I came to the custom sandbox preview (with the double renders to mimic collaborators) which depends on `@theme-init/CodeBlock`.

https://github.com/YousefED/SyncedStore/blob/e23a75ef0bf4b95bb012b4a5798854a5d3ef751c/docs/src/theme/CodeBlock/index.tsx#L10

Is that package available somewhere?

**Comment by YousefED** [comment]
This is a docusaurus feature. See https://docusaurus.io/docs/using-themes#for-plugin-authors

**Comment by echarles** [comment]
Docusaurus is awesome!
