### ISSUE TITLE
Local sync?

### ISSUE THREAD

**Issue by echarles** [YousefED/SyncedStore#46]
Is it possible to use `SyncedStore` without one of the Y.js providers ?

- https://docs.yjs.dev/ecosystem/connection-provider
- https://docs.yjs.dev/ecosystem/connection-provider

I wonder if `SyncedStore` could be used like any other state library (redux, mobx...) and only upgrade/configure it once you really need collaboration?

**Comment by YousefED** [comment]
Hi Eric!

Can you specify more what functionality you’re looking for exactly (what’s
the functionality you’d like to “keep”?).

It should be possible to use syncedstore, and just not connect any sync
provider.

Alternatively, perhaps the Reactive library could provide what you’re
looking for?

https://github.com/YousefED/reactive

**Comment by echarles** [comment]
> Can you specify more what functionality you’re looking for exactly (what’s
the functionality you’d like to “keep”?).

Just a local sync without depending on a y.js provider (so no webrtc, no websocket, no indexdb...).
I guess it should be possible to go throught the Y.Doc in memory and just update the store via that local Y.Doc.

> It should be possible to use syncedstore, and just not connect any sync provider.

Yes, but for non-syncing appliation, using a sync provider could not be mandatory.
I have looked for a "in-memory" sync provider, but did not find any.
Even if such a in-memory would exist, I guess it would create a data structure that would not be needed in case of local (non-syncing) state.

> Alternatively, perhaps the Reactive library could provide what you’relooking for? https://github.com/YousefED/reactive

Yes, I have looked at that and have opened a question on https://github.com/YousefED/reactive/issues/5 because I don't see how to use it from different React components.

**Comment by YousefED** [comment]
> Yes, but for non-syncing appliation, using a sync provider could not be mandatory.

A sync provider is not mandatory for SyncedStore, just like it's not mandatory for Yjs. If you just create a Y.Doc, everything will work in memory. Only if you want to persist data or enable collaboration, you'll need a sync provider.

Hope this makes sense! I'll close this issue for now, but feel free to reply with additional questions

**Comment by echarles** [comment]
Makes sense! Thx @YousefED
