### ISSUE TITLE
Feat: add Vue 3 composition api usage

### ISSUE THREAD

**Issue by sam585456525** [YousefED/SyncedStore#53]
Hi,thanks for this useful project. I found that there is only old option api usage in Vue example. Because Vue 3 has the powerful composition api just look like react hook, maybe it's a good idea to add composition features for Vue's users. If you agree with this proposal, I'd be glad to open a pr for it;)

**Comment by YousefED** [comment]
Hi @sam585456525 , welcome!

SyncedStore should work fine with the composition API, as it builds around Vue's reactivity feature.

Any PRs to clarify this in the documentation is definitely appreciated!
