### ISSUE TITLE
Text.insert is not a function

### ISSUE THREAD

**Issue by Toubat** [YousefED/SyncedStore#58]
I create a sandbox:
https://codesandbox.io/s/sandpack-project-forked-4p6tep?file=/src/App.vue

On the screen, click on "Insert" button, an error will raise that says "this.store.myText.text.insert is not a function". I have no idea what I did wrong.

**Comment by YousefED** [comment]
I think you only get this error when manually editing the input text, which is also bound to the text:

`<input v-model="store.myText.text" />`

Currently, we don't support two-way binding to Text models on inputs directly. Removing this binding should fix it
