### ISSUE TITLE
Yjs transact

### ISSUE THREAD

**Issue by skomlaebri** [YousefED/SyncedStore#66]
Hi, 

is there a way in SyncedStore to do doc transact as in Yjs, to reduce the number of update calls?

**Comment by gustavotoyota** [comment]
Pretty simple:
```
const doc = getYjsValue(store)

doc.transact(() => {
  // Transaction
})
```

**Comment by skomlaebri** [comment]
Thanks,  that what I ended up doing, I was curious to know if there was a way to avoid the conversion and not having to handle everything with the yjs Syntax.

**Comment by YousefED** [comment]
At this moment there's no build in SyncedStore transactions, but the proposed method should work well!
