### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by dl8sd11** [YousefED/SyncedStore#68]
After running `npm build`, it seems like some instances and functions are duplicated.

For example, there are two INTERNAL_SYMBOL in `packages\core\dist\syncedstore.js`

```
var INTERNAL_SYMBOL$1 = Symbol("INTERNAL_SYMBOL");
var INTERNAL_SYMBOL = Symbol("INTERNAL_SYMBOL");
```

**Comment by YousefED** [comment]
I can't reproduce this issue, let me know if you're still running into this after updating your repo
