### ISSUE TITLE
Support binary data

### ISSUE THREAD

**Issue by csbenjamin** [YousefED/SyncedStore#74]
I have been using yjs for some time now. And I usually store binary data in my yjs documents using Uint8Array objects. I wonder if you could add the option to store Uint8Array objects without using the boxed function.

**Comment by csbenjamin** [comment]
I actually thought I could use boxed to store Uint8Array, but apparently I can't.

**Comment by YousefED** [comment]
> I actually thought I could use boxed to store Uint8Array, but apparently I can't.

Hi @csbenjamin ,

Thanks for reporting. This is actually possible, a test has been added here: https://github.com/YousefED/SyncedStore/pull/82

Hope this works for you!

**Comment by YousefED** [comment]
My bad, it was a bug indeed, fixed in https://github.com/YousefED/SyncedStore/pull/83
