### ISSUE TITLE
Undo Redo Support

### ISSUE THREAD

**Issue by websiddu** [YousefED/SyncedStore#78]
Is there a way to do undo/redo using Synced Store?

**Comment by YousefED** [comment]
Yes @websiddu ! You should be able to use the regular Yjs [undomanager](https://docs.yjs.dev/api/undo-manager), e.g.:

```
const val = getYjsValuestore.value)

const undoManager = new Y.UndoManager(val)

// Do stuff to val (Let undoManager capture the updates)

undoManager.undo() // Revert the captured updates
```

Does this answer your question?
