### ISSUE TITLE
Pinia integration

### ISSUE THREAD

**Issue by websiddu** [YousefED/SyncedStore#90]
For react we could use mobx in conjunction with synced store, is there something simlar with pinia for vue3?

**Comment by YousefED** [comment]
Hi @websiddu. Have you tried using the Vue bindings? SyncedStore should integrate well with Vue: https://syncedstore.org/docs/vue

**Comment by texastoland** [comment]
@YousefED I was just reading your Vue bindings! Maybe they could be simplified by manually triggering a ref without the `reactive` proxy 👀

```js
export function enableVueBindings({ shallowRef, triggerRef }) { // Vue
  customReaction = undefined
  customCreateAtom = (name, onBecomeObserved) => {
    const ref = shallowRef()
    onBecomeObserved?.()
    return {
      reportObserved: () => ref.value // read
      reportChanged: () => triggerRef(ref) // write
    };
  };
}
```

Totally untested 😅
